LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

SingleSpaceBeforeFirstArg:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

TrailingComma:
  Enabled: false
AllCops:
  Exclude:
    - '*.gemspec'
    - 'tasks/**/*'
    - 'spec/**/*'
    - 'Rakefile'
